version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gofmt
    - goimports
    - bodyclose
    - misspell
    - nilerr
    - prealloc
    - gocritic
  settings:
    govet:
      enable:
        - shadow
    goimports:
      local-prefixes: github.com/jz-wilson/cloud-price-exporter
    errcheck:
      exclude-functions:
        - (net/http.ResponseWriter).Write
        - (*github.com/sirupsen/logrus.Entry).Fatalf
        - (*github.com/sirupsen/logrus.Entry).Fatal
        - (*github.com/sirupsen/logrus.Logger).Fatalf
        - (*github.com/sirupsen/logrus.Logger).Fatal
    gocritic:
      enabled-tags:
        - diagnostic
      disabled-tags:
        - style
        - opinionated
        - performance

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
